# Generated by Django 2.1.7 on 2019-02-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isconfirmed',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
