# Generated by Django 2.1.7 on 2019-02-17 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_isconfirmed_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doclocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filelocation', models.FileField(blank=True, null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='location',
        ),
        migrations.RemoveField(
            model_name='document',
            name='projects',
        ),
        migrations.DeleteModel(
            name='Documentlocation',
        ),
        migrations.AddField(
            model_name='doclocation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Document'),
        ),
        migrations.AddField(
            model_name='doclocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(through='login.Doclocation', to='login.Document'),
        ),
    ]
