# Generated by Django 2.1.7 on 2019-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190217_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
