# Generated by Django 2.1.7 on 2019-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
