# Generated by Django 2.1.7 on 2019-03-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_userprofile_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='semester',
        ),
        migrations.AddField(
            model_name='role',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
