# Generated by Django 2.1.7 on 2019-03-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_calendar_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='doclocation',
            name='approved',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='doclocation',
            name='reviews',
            field=models.TextField(blank=True, null=True),
        ),
    ]
