# Generated by Django 2.1.7 on 2019-03-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20190323_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doclocation',
            name='approved',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
